version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: meu-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/docker/volumes/postgres-data/_data

volumes:
  postgres-data:
