version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: meu-postgres
    environment:
      - DATABASE_URL: ${DATABASE_URL}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
